### ISSUE TITLE
Using curl instead of gh-cli

### ISSUE THREAD

**Issue by Okeanos** [coreos/actions-lib#11]
I recently had a look at how the "require file change"-composite action is set up and noticed that it uses bare `curl` statements to retrieve the PR information it needs.

Is there a particular reason that the [gh-cli](https://cli.github.com) isn't used for this? It is (to my knowledge) preinstalled on all GH provided runners and should make interacting with the API easier/more robust?

For example the `diffinfo` retrieval could be rewritten similar to:

```bash
diffinfo=$(gh pr view --repo "${{ github.event.pull_request.html_url }}" \
            --json 'files' \
            --jq '.files[] | select(.path == "${{ inputs.path }}")')
```

Instead of using:

```bash
diffinfo=$(curl --no-progress-meter \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ inputs.token || github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}" |
            jq '.files[] | select(.filename == "${{ inputs.path }}")')
```

The label-retrieval would look similarly like this:

```bash
label=$(gh pr view --repo "${{ github.event.pull_request.html_url }}" \
         --json 'labels' \
         --jq '.labels[] | select(.name == "${{ inputs.override-label }}")')
```

Additionally, by setting `GH_TOKEN` with a value of `${{ inputs.token || github.token }}` via the action environment authentication is fully handled.

**Comment by bgilbert** [comment]
It's because I didn't know about `gh` at the time.  I agree that that would have been a cleaner way to write it.

Is the current code causing any problems, or is this just a cleanup?

**Comment by Okeanos** [comment]
It would be a cleanup so to speak – I was effectively just curious about the details of this implementation. No action required :)

**Comment by bgilbert** [comment]
Okay, cool.  I don't think the cleanup is worth the effort to requalify the new implementation, so I'll go ahead and close.
